version: '3.8'

services:
  # ===== MODELOS QUE FUNCIONAM =====
  
  # Balanced Tier - Llama 8B (FUNCIONA)
  llama-8b-balanced:
    build:
      context: .
      dockerfile: containers/Dockerfile.llm-base
    image: llm-multi-base:latest
    container_name: llama-8b-balanced
    restart: unless-stopped
    environment:
      - MODEL_NAME=Llama 3.1 8B Balanced
      - MODEL_PATH=/app/models/llama/llama-3.1-8b-instruct-q4_k_m.gguf
      - SERVER_PORT=8000
      - GPU_LAYERS=30
      - CONTEXT_SIZE=4096
      - MODEL_SPECIALTIES=general,complex-tasks,multilingual
      - NVIDIA_VISIBLE_DEVICES=0
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    volumes:
      - ./models:/app/models:ro
      - ./config:/app/config:ro
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    networks:
      - llm-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Specialist Tier - CodeLlama (FUNCIONA)
  codellama-7b:
    build:
      context: .
      dockerfile: containers/Dockerfile.llm-base
    image: llm-multi-base:latest
    container_name: codellama-7b
    restart: unless-stopped
    environment:
      - MODEL_NAME=CodeLlama 7B Specialist
      - MODEL_PATH=/app/models/llama/codellama-7b-instruct-q4_k_m.gguf
      - SERVER_PORT=8000
      - GPU_LAYERS=30
      - CONTEXT_SIZE=4096
      - MODEL_SPECIALTIES=code,programming,debugging,development
      - NVIDIA_VISIBLE_DEVICES=0
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    volumes:
      - ./models:/app/models:ro
      - ./config:/app/config:ro
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    networks:
      - llm-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Balanced Tier - Mistral (FUNCIONA)
  mistral-7b-code:
    build:
      context: .
      dockerfile: containers/Dockerfile.llm-base
    image: llm-multi-base:latest
    container_name: mistral-7b-code
    restart: unless-stopped
    environment:
      - MODEL_NAME=Mistral 7B Code
      - MODEL_PATH=/app/models/mistral/mistral-7b-instruct-q4_k_m.gguf
      - SERVER_PORT=8000
      - GPU_LAYERS=30
      - CONTEXT_SIZE=8192
      - MODEL_SPECIALTIES=code,programming,technical
      - NVIDIA_VISIBLE_DEVICES=0
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    volumes:
      - ./models:/app/models:ro
      - ./config:/app/config:ro
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    networks:
      - llm-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Premium Tier - Solar (FUNCIONA)
  solar-10b-premium:
    build:
      context: .
      dockerfile: containers/Dockerfile.llm-base
    image: llm-multi-base:latest
    container_name: solar-10b-premium
    restart: unless-stopped
    environment:
      - MODEL_NAME=Solar 10.7B Premium
      - MODEL_PATH=/app/models/solar/solar-10.7b-instruct-q4_k_m.gguf
      - SERVER_PORT=8000
      - GPU_LAYERS=35
      - CONTEXT_SIZE=4096
      - MODEL_SPECIALTIES=complex-reasoning,high-quality,detailed-analysis
      - NVIDIA_VISIBLE_DEVICES=0
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    volumes:
      - ./models:/app/models:ro
      - ./config:/app/config:ro
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    networks:
      - llm-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # ===== GATEWAY CORRIGIDO =====
  smart-gateway-v2:
    build:
      context: ./gateway-v2
      dockerfile: Dockerfile
    image: llm-smart-gateway-v2:latest
    container_name: smart-gateway-v2
    restart: unless-stopped
    ports:
      - "8200:8200"
    environment:
      - GATEWAY_VERSION=2.0
      - LOG_LEVEL=INFO
    networks:
      - llm-network
    depends_on:
      - llama-8b-balanced
      - codellama-7b
      - mistral-7b-code
      - solar-10b-premium
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8200/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # ===== MONITORING =====
  monitoring:
    image: nginx:alpine
    container_name: llm-monitoring
    restart: unless-stopped
    ports:
      - "8300:80"
    volumes:
      - ./monitoring:/usr/share/nginx/html:ro
    networks:
      - llm-network

networks:
  llm-network:
    driver: bridge
